In [1]:
import pandas as pd

In [24]:
pd.read_csv('data/Hockey/SKATERS.csv')

,name,first,last,position,games,goals,assists,time,active,hof
0,Antti Aalto,1998,2001,C,151,11,17,1668.0,False,False
1,Wyatt Aamodt,2025,2025,D,2,1,0,34.0,True,False
2,Reg Abbott,1953,1953,C,3,0,0,NaN,False,False
3,Spencer Abbott,2014,2017,LW,2,0,0,14.0,False,False
4,Justin Abdelkader,2008,2020,LW,739,106,146,11010.0,False,False
...,...,...,...,...,...,...,...,...,...,...
7780,Jason Zucker,2012,2025,LW,770,217,206,11947.0,True,False
7781,Mike Zuke,1979,1986,C,455,86,196,NaN,False,False
7782,Rudy Zunich,1944,1944,D,2,0,0,NaN,False,False
7783,Valentin Zykov,2017,2020,LW,55,7,10,611.0,False,False
7784,Andrei Zyuzin,1998,2008,D,496,38,82,9007.0,False,False