In [1]:
import pandas as pd

In [25]:
df = pd.read_csv('data/Hockey/SKATERS.csv')

In [27]:
df[df['hof'] == True]

,name,first,last,position,games,goals,assists,time,active,hof
7,Sid Abel,1939,1954,C/LW,612,188,284,NaN,False,True
27,Jack Adams,1918,1927,C,173,81,44,NaN,False,True
64,Daniel Alfredsson,1996,2014,RW,1246,444,713,21478.0,False,True
74,Keith Allen,1954,1955,D,28,0,4,NaN,False,True
98,Glenn Anderson,1981,1996,RW,1129,498,601,NaN,False,True
...,...,...,...,...,...,...,...,...,...,...
7485,Shea Weber,2006,2021,D,1038,224,365,24958.0,False,True
7494,Cooney Weiland,1929,1939,C,509,173,162,NaN,False,True
7603,Doug Wilson,1978,1993,D,1024,237,590,NaN,False,True
7721,Steve Yzerman,1984,2006,C,1514,692,1063,9482.0,False,True
7777,Sergei Zubov,1993,2009,D,1068,152,619,19506.0,False,True